# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development-2.0

pool:
  vmImage: 'macOS-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      workingDirectory: ''
      tasks: 'assembleDebug'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'

  - task: CopyFiles@2
    inputs:
        Contents: '**/*_1.apk'
        TargetFolder:  '$(build.artifactStagingDirectory)'
        OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'HE-MAPP-ANDROID'
          publishLocation: 'Container'
          FileCopyOptions: 
  - task: AppCenterDistribute@3
    inputs:
        serverEndpoint: 'NHE_Android'
        appSlug: 'shivam.gupta-conduent.com/NHE'
        appFile: '**/*_1.apk'
        releaseNotesOption: 'input'
        releaseNotesInput: 'App Releases'
        destinationType: 'groups'

 