# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- code_review_development

pool:
  vmImage: 'macOS-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      workingDirectory: ''
      tasks: 'assembleDebug'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
  - task: PublishTestResults@2
    inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/testDevDebugUnitTest/TEST-*.xml'
        searchFolder: $(System.DefaultWorkingDirectory)

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: ./gradlew jacocoTestReport

  - task: PublishCodeCoverageResults@1
    inputs:
     codeCoverageTool: 'JaCoCo'
     summaryFileLocation: '/Users/runner/work/1/s/app/build/coverage/report/testReport.xml'
     pathToSources: '/Users/runner/work/1/s/app/src/main/java/'

  - task: PublishTestResults@2
    inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/testDevDebugUnitTest/TEST-*.xml'
        searchFolder: $(System.DefaultWorkingDirectory)
        
  - task: CopyFiles@2
    inputs:
        Contents: '**/*.apk'
        TargetFolder:  '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'HE-MAPP-ANDROID'
          publishLocation: 'Container'
      
  - task: Bash@3
    inputs:
      filePath: 'bash_script'
