# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- code_review_development

pool:
  vmImage: 'macOS-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      workingDirectory: ''
      tasks: 'assembleDebug'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

  - task: CopyFiles@2
    inputs:
        Contents: '**/*.apk'
        TargetFolder:  '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'HE-MAPP-ANDROID'
          publishLocation: 'Container'
      
  - task: Bash@3
    inputs:
      filePath: 'bash_script'

  - script: ./gradlew jacocoTestReport

  - task: PublishTestResults@2
      condition: succeededOrFailed()
    inputs:
        testResultsFormat: 'JUnit'
        # testResultsFiles: '**/test/TEST-*.xml'
        searchFolder: $(System.DefaultWorkingDirectory)
        displayName: "Publish Test Results"

- task: PublishCodeCoverageResults@1
   condition: succeededOrFailed()
     inputs:
     codeCoverageTool: 'Jacoco'
     summaryFileLocation: 
'$(Build.BuildDirectory)/app/build/coverage/report/html/index.html'
 displayName: "Publish Code Coverage Results"


     

