# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- code_review_development

pool:
  vmImage: 'macOS-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
      publishJunitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleDebug'
  - task: Bash@3
    inputs:
      filePath: 'bash_script'
  - task: Bash@3
    inputs:
      filePath: 'bash_script'


 
